language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.0
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    
 licenses:
    - '.+'

script:
    - ./gradlew test
